FROM debian:buster-slim
ADD bin/gor_RESURFACE_LOGGER_x64.tar.gz  /bin/
ENTRYPOINT [ "gor", "--input-raw", ":80", "--input-raw-track-response", "--output-resurface", "http://localhost:4001/message", "--output-resurface-rules", "include debug" ]
