FROM debian:buster-slim
ADD bin/gor_RESURFACE_LOGGER_x64.tar.gz  /bin/
ENTRYPOINT gor --input-raw :$APP_PORT --input-raw-track-response --output-resurface $USAGE_LOGGERS_URL --output-resurface-rules "$USAGE_LOGGERS_RULES"
